version: '3.8'

services:

  cnprontoclin:
    image: postgres:latest
    container_name: cnprontoclin
    environment:
      POSTGRES_DB: dbprontoclin
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: prontoclin@gmail.com
    ports:
      - "5432:5432" 
    networks:
      - my-networks  
    restart: always  

  pgadminprontoclin:
    image: dpage/pgadmin4
    container_name: pgadminprontoclin
    environment:
      PGADMIN_DEFAULT_EMAIL: prontoclin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres 

    ports:
      - "15432:80"  
    networks:
      - my-networks 
    restart: always

  springboot-app:
    build:
      context: .  
      dockerfile: ./dockerfile  # Caminho para o Dockerfile
    container_name: springprontoclin
    ports:

      - "8081:8081"  # Mapeia a porta 8080 no host para a porta 8080 no container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cnprontoclin:5432/dbprontoclin  # URL de conexão com o banco
      SPRING_DATASOURCE_USERNAME: prontoclin@gmail.com 
      SPRING_DATASOURCE_PASSWORD: postgres 
    networks:
      - my-networks 
    depends_on:
      - cnprontoclin
    restart: always
networks:
  my-networks:
    driver: bridge 
