# Etapa 1: Construir a aplicação React (Frontend)
FROM node:18-alpine AS react-build

WORKDIR /app

# Copiar o package.json e o package-lock.json
COPY ReactProntoClin/prontoclin/package*.json /app/

# Instalar dependências do React
RUN npm install

# Copiar o código fonte da aplicação React
COPY ReactProntoClin/prontoclin /app/

# Construir a aplicação React para produção
RUN npm run build

# Etapa 2: Configuração do Nginx
FROM nginx:alpine

# Copiar os arquivos construídos do React para o diretório do Nginx
COPY --from=react-build /app/build /usr/share/nginx/html

# Copiar a configuração personalizada do Nginx
COPY ReactProntoClin/prontoclin/nginx.conf /etc/nginx/nginx.conf

# Expor a porta 80 (do frontend)
EXPOSE 80

# Iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]
